package cn.clxuanye;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2018-05-07T12:33:39.992+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebServiceClient(name = "CheneyThinkerWebServiceImpl", 
                  wsdlLocation = "http://localhost:8080/CheneyThinker?wsdl",
                  targetNamespace = "http://www.clxuanye.cn") 
public class CheneyThinkerWebServiceImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.clxuanye.cn", "CheneyThinkerWebServiceImpl");
    public final static QName CheneyThinkerWebServiceImplPort = new QName("http://www.clxuanye.cn", "CheneyThinkerWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/CheneyThinker?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CheneyThinkerWebServiceImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/CheneyThinker?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CheneyThinkerWebServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CheneyThinkerWebServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CheneyThinkerWebServiceImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CheneyThinkerWebServiceImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CheneyThinkerWebServiceImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CheneyThinkerWebServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CheneyThinkerWebService
     */
    @WebEndpoint(name = "CheneyThinkerWebServiceImplPort")
    public CheneyThinkerWebService getCheneyThinkerWebServiceImplPort() {
        return super.getPort(CheneyThinkerWebServiceImplPort, CheneyThinkerWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CheneyThinkerWebService
     */
    @WebEndpoint(name = "CheneyThinkerWebServiceImplPort")
    public CheneyThinkerWebService getCheneyThinkerWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CheneyThinkerWebServiceImplPort, CheneyThinkerWebService.class, features);
    }

}
